agent_name = "catalan-voice-agent"
image = "DOCKER_USERNAME/catalan-voice-agent:0.1"
secret_set = "catalan-voice-agent-secrets"
agent_profile = "agent-1x"
region = "eu-central"

[scaling]
    min_agents = 0
    max_agents = 10
